#--------------------------------------------------------------------------------------
#
# This is a configuration file for a scraper that scrapes Glassdoor job postings
# for various job titles related to data engineering, with settings for
# job titles, number of jobs, URLs, driver path, output paths, and other options.
#
#--------------------------------------------------------------------------------------
---
# The list of jobs somehow similar to data engineering:
# https://resumeworded.com/career-profiles/data-engineer-career-profile#anchor_link2_job_4
jobs_titles:
    default: "Data Engineer"
    similar:
        - "Big Data Engineer"
        - "Data Architecture"
        - "Data Manager"
        - "Data Architect"
        - "Data Specialist"
        - "Business Intelligence Engineer"
        - "Business Intelligence Developer"
        - "ETL Developer"
        - "Data Warehouse Engineer"
        - "Data Consultant"
        - "Database Engineer"
        - "Database Developer"
        - "Analytics Consultant"
# The cap in glassdoor is 900 (30 postings x 30 pages) in this kind of implementation.
# Empirically proofed cap is < 2000 (scraping directly through the job postings) until you will not be blocked.

# In our case countries, but they could be cities as well
locations:
    # Usually US based
    default: ""
    # US + Canada + Europe + Israel
    others:
        - "United States"
        - "Canada"
        - "Austria"
        - "Belgium"
        - "Bulgaria"
        - "Croatia"
        - "Cyprus"
        - "Czech Republic"
        - "Denmark"
        - "Estonia"
        - "Finland"
        - "France"
        - "Greece"
        - "Spain"
        - "Netherlands"
        - "Ireland"
        - "Iceland"
        - "Liechtenstein"
        - "Lithuania"
        - "Luxembourg"
        - "Latvia"
        - "Malta"
        - "Germany"
        - "Norway"
        - "Poland"
        - "Portugal"
        - "Romania"
        - "Slovakia"
        - "Slovenia"
        - "Sweden"
        - "Switzerland"
        - "Hungary"
        - "Italy"
        - "Israel"
        - "Turkey"
        - "United Kingdom"
jobs_number: 900
url:
    # base + job + keyword + job + location + ?
    001_base: "https://www.glassdoor.com/Job/jobs.htm?suggestCount=0&suggestChosen=false&clickSource=searchBtn&typedKeyword="
    002_keyword: "&sc.keyword="
    # If empty the default location is US
    003_location: "&locT=&locId=&jobType="
# Update this path for your driver app... or write "auto-install", if you want to auto-install for you Chrome/any browser
# driver_path: "auto-install"
driver_path: "C:\\Program Files (x86)\\Google\\Chrome\\Application\\chromedriver.exe"
output_path:
    main: "data"
    raw: "RAW"
    clean: "clean"
# In Python None value is not equivalent to null in Typescript.
# Empty string complies with mypy better.
NA_value: ""
debug_mode: false
# glassdoor charset
encoding: "utf-8"
